name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clean install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Type checking
      run: tsc --noEmit

    - name: Build
      run: npm run build
